general.import = ["~/.config/alacritty/cyberdream.toml"]
[env]
TERM = "alacritty-direct"

[window]
padding.x = 5
padding.y = 5

decorations = "Buttonless"
opacity = 0.9
blur = true

option_as_alt = "Both"

[font]
# normal.family = "FiraCode Nerd Font Mono"
normal.family = "Hack Nerd Font Mono"
# normal.family = "MonoLisa Custom"
# normal.style = "Regular Italic"
size = 12

[font.offset]
x = 1
y = 0
